// Capy Yara Adventures — French Daily-Trail Lessons (12)
// Schema mirrors JADSON_LESSONS from lessons.html exactly.
// NOTE: The `en` field of each vocab card holds the FRENCH word (target language being learned).
// The `pt` field holds the Brazilian-Portuguese translation. The runner reads `.en` as
// "the word to learn"; TTS language is switched via `lang: 'fr'`.
const LESSONS_FR = [
  {
    id: 201, title: "Les Salutations", emoji: "👋", lang: "fr",
    verbs: ["Saluer", "Dire bonjour", "Remercier", "Demander"],
    vocab: [
      {en: "Bonjour", pt: "Olá / Bom dia"},
      {en: "Salut", pt: "Oi (informal)"},
      {en: "Au revoir", pt: "Tchau / Até logo"},
      {en: "Merci", pt: "Obrigado(a)"},
      {en: "S'il vous plaît", pt: "Por favor (formal)"},
      {en: "Oui", pt: "Sim"},
      {en: "Non", pt: "Não"},
      {en: "Comment ça va ?", pt: "Como você está?"},
    ],
    expressions: [
      {expr: "Enchanté(e)", meaning: "Prazer em conhecer.", example: "Bonjour, enchanté de vous rencontrer."},
      {expr: "À bientôt", meaning: "Até breve.", example: "Au revoir et à bientôt !"},
      {expr: "Bonne journée", meaning: "Tenha um bom dia.", example: "Merci, bonne journée !"},
      {expr: "De rien", meaning: "De nada.", example: "— Merci ! — De rien."},
    ],
    sentences: [
      "Bonjour, comment ça va ?",
      "Salut, ça va bien.",
      "Merci beaucoup, monsieur.",
      "Au revoir et à bientôt.",
      "Oui, s'il vous plaît.",
      "Non, merci.",
      "Enchanté de vous rencontrer.",
      "Bonne journée à vous !",
    ],
    grammar: {
      title: "Tu vs Vous — Formal e Informal",
      rules: [
        "<b>Tu</b> = informal, usado com amigos, família e crianças.",
        "<b>Vous</b> = formal (uma pessoa) OU plural (várias pessoas).",
        "Em dúvida, use <b>vous</b> — é sempre seguro e educado.",
      ],
      table: {
        headers: ["Situação", "Pronome", "Exemplo"],
        rows: [
          ["Amigo", "Tu", "Salut, comment vas-tu ?"],
          ["Estranho", "Vous", "Bonjour, comment allez-vous ?"],
          ["Plural", "Vous", "Bonjour, comment allez-vous ?"],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'Olá' (formal) em francês?", a: "Bonjour", opts: ["Salut", "Bonjour", "Merci", "Au revoir"]},
      {q: "Qual é a forma educada de 'por favor'?", a: "S'il vous plaît", opts: ["Merci", "De rien", "S'il vous plaît", "Bonjour"]},
      {q: "Como se despedir em francês?", a: "Au revoir", opts: ["Bonjour", "Salut", "Au revoir", "Oui"]},
      {q: "Como responder a 'Merci' ?", a: "De rien", opts: ["Merci", "De rien", "Oui", "Salut"]},
      {q: "Qual saudação é informal?", a: "Salut", opts: ["Bonjour", "Salut", "Au revoir", "Bonne journée"]},
    ],
    speak: [
      "Bonjour, comment ça va ?",
      "Merci beaucoup !",
      "Au revoir, à bientôt.",
      "S'il vous plaît, monsieur.",
      "Enchanté de vous rencontrer.",
    ],
  },

  {
    id: 202, title: "Les Chiffres (1-10)", emoji: "🔢", lang: "fr",
    verbs: ["Compter", "Additionner", "Soustraire", "Numéroter"],
    vocab: [
      {en: "Un", pt: "Um (1)"},
      {en: "Deux", pt: "Dois (2)"},
      {en: "Trois", pt: "Três (3)"},
      {en: "Quatre", pt: "Quatro (4)"},
      {en: "Cinq", pt: "Cinco (5)"},
      {en: "Six", pt: "Seis (6)"},
      {en: "Sept", pt: "Sete (7)"},
      {en: "Huit", pt: "Oito (8)"},
      {en: "Neuf", pt: "Nove (9)"},
      {en: "Dix", pt: "Dez (10)"},
    ],
    expressions: [
      {expr: "Combien ?", meaning: "Quanto?", example: "Combien coûte ce livre ?"},
      {expr: "Le numéro un", meaning: "O número um.", example: "Tu es le numéro un !"},
      {expr: "Deux fois", meaning: "Duas vezes.", example: "Je le dis deux fois."},
      {expr: "À trois !", meaning: "Conto até três!", example: "Un, deux, à trois !"},
    ],
    sentences: [
      "J'ai un chat.",
      "Il y a deux livres.",
      "Nous sommes trois.",
      "Elle a quatre amis.",
      "Cinq plus cinq égale dix.",
      "Six et sept font treize.",
      "J'ai huit ans.",
      "Il y a neuf pommes.",
    ],
    grammar: {
      title: "Les Nombres — Liaison e Pronúncia",
      rules: [
        "<b>Six</b> e <b>dix</b> têm pronúncias diferentes: sozinhos /sis/ /dis/, antes de consoante /si/ /di/.",
        "<b>Cinq</b> antes de consoante pode perder o /k/ final.",
        "<b>Neuf</b> antes de 'ans' ou 'heures' vira /nœv/: neuf ans → /nœv ɑ̃/.",
      ],
      table: {
        headers: ["Nombre", "Écriture", "Exemple"],
        rows: [
          ["1", "Un / Une", "un livre / une table"],
          ["2", "Deux", "deux chats"],
          ["5", "Cinq", "cinq euros"],
          ["10", "Dix", "dix minutes"],
        ],
      },
    },
    quiz: [
      {q: "Como se diz '3' em francês?", a: "Trois", opts: ["Deux", "Trois", "Quatre", "Six"]},
      {q: "Qual é o número '7' ?", a: "Sept", opts: ["Six", "Sept", "Huit", "Neuf"]},
      {q: "Combien font 5 + 5 ?", a: "Dix", opts: ["Neuf", "Dix", "Huit", "Sept"]},
      {q: "Como se escreve '1' (masculino)?", a: "Un", opts: ["Une", "Un", "On", "En"]},
      {q: "Qual é o número '9' ?", a: "Neuf", opts: ["Sept", "Huit", "Neuf", "Dix"]},
    ],
    speak: [
      "Un, deux, trois.",
      "J'ai cinq ans.",
      "Il y a dix pommes.",
      "Combien ça coûte ?",
      "Sept plus trois font dix.",
    ],
  },

  {
    id: 203, title: "Les Couleurs", emoji: "🎨", lang: "fr",
    verbs: ["Voir", "Peindre", "Choisir", "Aimer"],
    vocab: [
      {en: "Rouge", pt: "Vermelho"},
      {en: "Bleu", pt: "Azul"},
      {en: "Vert", pt: "Verde"},
      {en: "Jaune", pt: "Amarelo"},
      {en: "Noir", pt: "Preto"},
      {en: "Blanc", pt: "Branco"},
      {en: "Rose", pt: "Rosa"},
      {en: "Orange", pt: "Laranja"},
    ],
    expressions: [
      {expr: "Voir la vie en rose", meaning: "Ver a vida cor de rosa.", example: "Depuis hier, je vois la vie en rose."},
      {expr: "Être rouge comme une tomate", meaning: "Ficar vermelho como tomate.", example: "Il est rouge comme une tomate !"},
      {expr: "Avoir une peur bleue", meaning: "Ter muito medo.", example: "J'ai une peur bleue des araignées."},
      {expr: "Nuit blanche", meaning: "Noite em claro.", example: "J'ai passé une nuit blanche."},
    ],
    sentences: [
      "La voiture est rouge.",
      "Le ciel est bleu.",
      "L'herbe est verte.",
      "Le soleil est jaune.",
      "Le chat est noir.",
      "La maison est blanche.",
      "J'aime la couleur rose.",
      "L'orange est ma couleur préférée.",
    ],
    grammar: {
      title: "Concordância das Cores (Adjetivos)",
      rules: [
        "As cores são <b>adjetivos</b> e concordam em gênero e número com o substantivo.",
        "Masculino → <b>vert</b> | Feminino → <b>verte</b> | Plural → <b>verts/vertes</b>.",
        "<b>Rose, orange, jaune</b> são invariáveis no singular: une robe rose, une fleur orange.",
      ],
      table: {
        headers: ["Masculino", "Feminino", "Tradução"],
        rows: [
          ["noir", "noire", "preto/preta"],
          ["blanc", "blanche", "branco/branca"],
          ["vert", "verte", "verde"],
          ["bleu", "bleue", "azul"],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'vermelho' em francês?", a: "Rouge", opts: ["Rose", "Rouge", "Orange", "Jaune"]},
      {q: "Qual é o feminino de 'blanc' ?", a: "Blanche", opts: ["Blanc", "Blanche", "Blancs", "Blanches"]},
      {q: "'Le ciel est ___' (azul)", a: "bleu", opts: ["bleue", "bleu", "blanc", "noir"]},
      {q: "Qual cor significa 'preto' ?", a: "Noir", opts: ["Blanc", "Noir", "Vert", "Bleu"]},
      {q: "'Une robe ___' (rosa)", a: "rose", opts: ["rose", "roses", "rouge", "rosée"]},
    ],
    speak: [
      "La voiture est rouge.",
      "J'aime le bleu.",
      "Le chat noir dort.",
      "Une fleur jaune et orange.",
      "Ma robe préférée est verte.",
    ],
  },

  {
    id: 204, title: "La Famille", emoji: "👨‍👩‍👧‍👦", lang: "fr",
    verbs: ["Aimer", "Présenter", "Connaître", "Vivre"],
    vocab: [
      {en: "La mère", pt: "A mãe"},
      {en: "Le père", pt: "O pai"},
      {en: "Le frère", pt: "O irmão"},
      {en: "La sœur", pt: "A irmã"},
      {en: "Les parents", pt: "Os pais"},
      {en: "Le fils", pt: "O filho"},
      {en: "La fille", pt: "A filha"},
      {en: "La famille", pt: "A família"},
    ],
    expressions: [
      {expr: "C'est ma famille", meaning: "Esta é minha família.", example: "Regarde, c'est ma famille !"},
      {expr: "Tel père, tel fils", meaning: "Tal pai, tal filho.", example: "Tel père, tel fils, il adore le foot."},
      {expr: "Être de la famille", meaning: "Ser da família.", example: "Tu es de la famille maintenant."},
      {expr: "Avoir un frère/une sœur", meaning: "Ter um irmão/uma irmã.", example: "J'ai un frère et deux sœurs."},
    ],
    sentences: [
      "Ma mère est très gentille.",
      "Mon père travaille beaucoup.",
      "J'ai un frère et une sœur.",
      "Mes parents habitent à Paris.",
      "Sa fille a cinq ans.",
      "Notre famille est grande.",
      "Le fils de Marie est petit.",
      "Ma sœur aime le chocolat.",
    ],
    grammar: {
      title: "Adjetivos Possessivos",
      rules: [
        "Os possessivos concordam com o <b>substantivo possuído</b>, não com o dono.",
        "Masc. sing.: <b>mon, ton, son</b> | Fem. sing.: <b>ma, ta, sa</b> | Plural: <b>mes, tes, ses</b>.",
        "Antes de vogal, usa-se a forma masculina mesmo no feminino: <b>mon amie</b> (não 'ma amie').",
      ],
      table: {
        headers: ["Pessoa", "Masc.", "Fem.", "Plural"],
        rows: [
          ["eu", "mon père", "ma mère", "mes parents"],
          ["você", "ton père", "ta mère", "tes parents"],
          ["ele/ela", "son père", "sa mère", "ses parents"],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'a mãe' em francês?", a: "La mère", opts: ["Le père", "La mère", "La sœur", "La fille"]},
      {q: "Qual é o masculino de 'la sœur' ?", a: "Le frère", opts: ["Le père", "Le fils", "Le frère", "Le parent"]},
      {q: "'___ père est gentil.' (meu)", a: "Mon", opts: ["Ma", "Mon", "Mes", "Ton"]},
      {q: "'___ mère travaille.' (minha)", a: "Ma", opts: ["Mon", "Ma", "Mes", "Sa"]},
      {q: "Como se diz 'os pais' em francês?", a: "Les parents", opts: ["Les enfants", "Les parents", "La famille", "Les frères"]},
    ],
    speak: [
      "Voici ma famille.",
      "Mon père s'appelle Paul.",
      "Ma mère est française.",
      "J'ai deux sœurs.",
      "Mes parents habitent à Lyon.",
    ],
  },

  {
    id: 205, title: "Être & Avoir", emoji: "✨", lang: "fr",
    verbs: ["Être", "Avoir", "Exister", "Posséder"],
    vocab: [
      {en: "Je suis", pt: "Eu sou/estou"},
      {en: "Tu es", pt: "Você é/está"},
      {en: "Il est", pt: "Ele é/está"},
      {en: "Elle est", pt: "Ela é/está"},
      {en: "J'ai", pt: "Eu tenho"},
      {en: "Tu as", pt: "Você tem"},
      {en: "Il a", pt: "Ele tem"},
      {en: "Nous sommes", pt: "Nós somos/estamos"},
      {en: "Nous avons", pt: "Nós temos"},
    ],
    expressions: [
      {expr: "J'ai faim", meaning: "Estou com fome.", example: "J'ai faim, allons manger !"},
      {expr: "J'ai soif", meaning: "Estou com sede.", example: "J'ai soif, je veux de l'eau."},
      {expr: "Avoir X ans", meaning: "Ter X anos.", example: "J'ai vingt ans."},
      {expr: "Être en retard", meaning: "Estar atrasado.", example: "Je suis en retard, désolé !"},
    ],
    sentences: [
      "Je suis étudiant.",
      "Tu es très gentil.",
      "Il est français.",
      "Nous sommes amis.",
      "J'ai un chien.",
      "Tu as une voiture.",
      "Elle a vingt ans.",
      "Nous avons faim.",
    ],
    grammar: {
      title: "Être et Avoir — Os Dois Verbos Essenciais",
      rules: [
        "<b>Être</b> (ser/estar) e <b>Avoir</b> (ter) são os verbos mais usados em francês.",
        "Eles são <b>irregulares</b> — devem ser memorizados.",
        "Para idade, usa-se <b>avoir</b>: 'J'ai 20 ans' (literalmente 'eu tenho 20 anos').",
      ],
      table: {
        headers: ["Pronome", "Être", "Avoir"],
        rows: [
          ["je / j'", "suis", "ai"],
          ["tu", "es", "as"],
          ["il / elle", "est", "a"],
          ["nous", "sommes", "avons"],
          ["vous", "êtes", "avez"],
          ["ils / elles", "sont", "ont"],
        ],
      },
    },
    quiz: [
      {q: "'Je ___ étudiant.' (ser)", a: "suis", opts: ["es", "suis", "ai", "est"]},
      {q: "'Tu ___ une voiture.' (ter)", a: "as", opts: ["es", "as", "a", "ai"]},
      {q: "Como dizer 'eu tenho 20 anos' ?", a: "J'ai vingt ans", opts: ["Je suis vingt ans", "J'ai vingt ans", "Je vingt ans", "J'es vingt ans"]},
      {q: "'Nous ___ amis.' (ser)", a: "sommes", opts: ["sont", "êtes", "sommes", "avons"]},
      {q: "'Elle ___ un chat.' (ter)", a: "a", opts: ["est", "a", "as", "ai"]},
    ],
    speak: [
      "Je suis brésilien.",
      "J'ai vingt-cinq ans.",
      "Tu es très gentil.",
      "Nous avons faim.",
      "Elle est ma sœur.",
    ],
  },

  {
    id: 206, title: "La Nourriture", emoji: "🥐", lang: "fr",
    verbs: ["Manger", "Boire", "Cuisiner", "Goûter"],
    vocab: [
      {en: "Le pain", pt: "O pão"},
      {en: "Le fromage", pt: "O queijo"},
      {en: "L'eau", pt: "A água"},
      {en: "La pomme", pt: "A maçã"},
      {en: "Le café", pt: "O café"},
      {en: "Le lait", pt: "O leite"},
      {en: "La viande", pt: "A carne"},
      {en: "Les légumes", pt: "Os legumes"},
    ],
    expressions: [
      {expr: "Bon appétit !", meaning: "Bom apetite!", example: "Le repas est prêt, bon appétit !"},
      {expr: "J'ai très faim", meaning: "Estou com muita fome.", example: "Après le sport, j'ai très faim."},
      {expr: "C'est délicieux", meaning: "Está delicioso.", example: "Ce fromage, c'est délicieux !"},
      {expr: "À table !", meaning: "À mesa! (Vamos comer!)", example: "Les enfants, à table !"},
    ],
    sentences: [
      "Je mange du pain.",
      "Elle boit de l'eau.",
      "Nous aimons le fromage.",
      "Le café est chaud.",
      "Tu manges une pomme.",
      "Les légumes sont frais.",
      "Il boit du lait le matin.",
      "La viande est bonne.",
    ],
    grammar: {
      title: "Os Artigos Partitivos (du, de la, de l')",
      rules: [
        "Usados para indicar uma <b>quantidade indefinida</b> de algo (um pouco de).",
        "<b>du</b> + masculino: du pain, du café | <b>de la</b> + feminino: de la viande.",
        "<b>de l'</b> antes de vogal: de l'eau, de l'huile.",
        "Na negativa, todos viram <b>de</b>: Je ne mange pas <b>de</b> pain.",
      ],
      table: {
        headers: ["Artigo", "Uso", "Exemplo"],
        rows: [
          ["du", "masc.", "Je mange du pain."],
          ["de la", "fem.", "Je bois de la limonade."],
          ["de l'", "vogal", "Je bois de l'eau."],
          ["des", "plural", "Je mange des légumes."],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'o pão' em francês?", a: "Le pain", opts: ["Le pain", "Le fromage", "Le lait", "La viande"]},
      {q: "'Je bois ___ eau.' (artigo correto)", a: "de l'", opts: ["du", "de la", "de l'", "des"]},
      {q: "'Je mange ___ pain.'", a: "du", opts: ["du", "de la", "de l'", "des"]},
      {q: "Como se diz 'a maçã' em francês?", a: "La pomme", opts: ["Le pain", "La pomme", "La poire", "Le pomme"]},
      {q: "'Les ___ sont frais.' (legumes)", a: "légumes", opts: ["fromages", "légumes", "viandes", "pains"]},
    ],
    speak: [
      "Je mange du pain et du fromage.",
      "Bon appétit !",
      "Tu veux du café ?",
      "L'eau est froide.",
      "J'aime les légumes verts.",
    ],
  },

  {
    id: 207, title: "Les Jours et les Mois", emoji: "📅", lang: "fr",
    verbs: ["Planifier", "Dater", "Programmer", "Attendre"],
    vocab: [
      {en: "Lundi", pt: "Segunda-feira"},
      {en: "Mardi", pt: "Terça-feira"},
      {en: "Mercredi", pt: "Quarta-feira"},
      {en: "Jeudi", pt: "Quinta-feira"},
      {en: "Vendredi", pt: "Sexta-feira"},
      {en: "Samedi", pt: "Sábado"},
      {en: "Dimanche", pt: "Domingo"},
      {en: "Janvier", pt: "Janeiro"},
      {en: "Février", pt: "Fevereiro"},
      {en: "Aujourd'hui", pt: "Hoje"},
      {en: "Demain", pt: "Amanhã"},
    ],
    expressions: [
      {expr: "Quel jour sommes-nous ?", meaning: "Que dia é hoje?", example: "Quel jour sommes-nous ? — Mardi."},
      {expr: "À demain", meaning: "Até amanhã.", example: "Bonne nuit, à demain !"},
      {expr: "La semaine prochaine", meaning: "Na semana que vem.", example: "On se voit la semaine prochaine."},
      {expr: "Le week-end", meaning: "O fim de semana.", example: "Bon week-end à tous !"},
    ],
    sentences: [
      "Aujourd'hui, c'est lundi.",
      "Demain, c'est mardi.",
      "Je travaille du lundi au vendredi.",
      "Samedi, je vais au cinéma.",
      "Dimanche, je reste à la maison.",
      "Mon anniversaire est en janvier.",
      "Février est le mois le plus court.",
      "Quel jour sommes-nous ?",
    ],
    grammar: {
      title: "Dias e Meses — Sem Maiúscula!",
      rules: [
        "Em francês, dias e meses são escritos com <b>letra minúscula</b>: lundi, janvier.",
        "Para dizer 'na segunda' (todas as segundas), use <b>le lundi</b>.",
        "Para dizer 'em janeiro', use <b>en janvier</b> ou <b>au mois de janvier</b>.",
      ],
      table: {
        headers: ["Estrutura", "Significado", "Exemplo"],
        rows: [
          ["lundi", "esta segunda", "Lundi, je travaille."],
          ["le lundi", "todas as segundas", "Le lundi, je nage."],
          ["en janvier", "em janeiro", "En janvier, il fait froid."],
        ],
      },
    },
    quiz: [
      {q: "Qual é o primeiro dia útil da semana?", a: "Lundi", opts: ["Dimanche", "Lundi", "Mardi", "Samedi"]},
      {q: "Como se diz 'hoje' em francês?", a: "Aujourd'hui", opts: ["Demain", "Hier", "Aujourd'hui", "Maintenant"]},
      {q: "Qual é o mês de janeiro?", a: "Janvier", opts: ["Février", "Janvier", "Juin", "Juillet"]},
      {q: "'___ , c'est samedi.' (amanhã)", a: "Demain", opts: ["Aujourd'hui", "Demain", "Hier", "Lundi"]},
      {q: "Como se diz 'domingo' ?", a: "Dimanche", opts: ["Samedi", "Dimanche", "Vendredi", "Mercredi"]},
    ],
    speak: [
      "Aujourd'hui, c'est lundi.",
      "Demain, je vais travailler.",
      "Mon anniversaire est en février.",
      "Bon week-end !",
      "Samedi et dimanche, je me repose.",
    ],
  },

  {
    id: 208, title: "L'Heure", emoji: "⏰", lang: "fr",
    verbs: ["Demander l'heure", "Indiquer", "Attendre", "Arriver"],
    vocab: [
      {en: "Quelle heure est-il ?", pt: "Que horas são?"},
      {en: "Il est trois heures", pt: "São três horas"},
      {en: "Midi", pt: "Meio-dia"},
      {en: "Minuit", pt: "Meia-noite"},
      {en: "Et quart", pt: "E quinze"},
      {en: "Et demie", pt: "E meia"},
      {en: "Du matin", pt: "Da manhã"},
      {en: "Du soir", pt: "Da noite"},
    ],
    expressions: [
      {expr: "À quelle heure ?", meaning: "A que horas?", example: "À quelle heure on se voit ?"},
      {expr: "Être à l'heure", meaning: "Estar na hora.", example: "Je suis toujours à l'heure."},
      {expr: "Il est tard", meaning: "É tarde.", example: "Il est tard, je vais dormir."},
      {expr: "Il est tôt", meaning: "É cedo.", example: "Il est tôt, le café n'est pas ouvert."},
    ],
    sentences: [
      "Quelle heure est-il ?",
      "Il est trois heures.",
      "Il est midi.",
      "Il est minuit.",
      "Il est dix heures et quart.",
      "Il est sept heures et demie.",
      "Il est huit heures du matin.",
      "Il est neuf heures du soir.",
    ],
    grammar: {
      title: "Como Dizer as Horas",
      rules: [
        "Estrutura básica: <b>Il est</b> + número + <b>heure(s)</b>.",
        "<b>Et quart</b> = e 15 | <b>Et demie</b> = e 30 | <b>Moins le quart</b> = 15 para.",
        "<b>Midi</b> e <b>Minuit</b> não levam 'heures': Il est midi (não 'midi heures').",
      ],
      table: {
        headers: ["Horário", "Em Francês"],
        rows: [
          ["3:00", "Il est trois heures."],
          ["3:15", "Il est trois heures et quart."],
          ["3:30", "Il est trois heures et demie."],
          ["3:45", "Il est quatre heures moins le quart."],
        ],
      },
    },
    quiz: [
      {q: "Como perguntar 'que horas são' ?", a: "Quelle heure est-il ?", opts: ["Quel jour est-il ?", "Quelle heure est-il ?", "Comment ça va ?", "Où es-tu ?"]},
      {q: "Como se diz 'meio-dia' ?", a: "Midi", opts: ["Minuit", "Midi", "Matin", "Soir"]},
      {q: "'Il est trois heures ___' (e meia)", a: "et demie", opts: ["et quart", "et demie", "moins le quart", "et trente"]},
      {q: "Como se diz 'meia-noite' ?", a: "Minuit", opts: ["Midi", "Minuit", "Nuit", "Soir"]},
      {q: "'Il est huit heures ___' (da manhã)", a: "du matin", opts: ["du soir", "du matin", "de la nuit", "du jour"]},
    ],
    speak: [
      "Quelle heure est-il ?",
      "Il est midi.",
      "Il est trois heures et quart.",
      "Il est sept heures et demie du matin.",
      "À quelle heure tu arrives ?",
    ],
  },

  {
    id: 209, title: "La Météo", emoji: "🌦️", lang: "fr",
    verbs: ["Faire", "Pleuvoir", "Neiger", "Briller"],
    vocab: [
      {en: "Il fait beau", pt: "Está bom (tempo)"},
      {en: "Il fait froid", pt: "Está frio"},
      {en: "Il pleut", pt: "Está chovendo"},
      {en: "Il neige", pt: "Está nevando"},
      {en: "Le soleil", pt: "O sol"},
      {en: "Le vent", pt: "O vento"},
      {en: "L'été", pt: "O verão"},
      {en: "L'hiver", pt: "O inverno"},
    ],
    expressions: [
      {expr: "Quel temps fait-il ?", meaning: "Como está o tempo?", example: "Quel temps fait-il aujourd'hui ?"},
      {expr: "Il fait un temps magnifique", meaning: "O tempo está ótimo.", example: "Sortons, il fait un temps magnifique !"},
      {expr: "Il pleut des cordes", meaning: "Está chovendo muito.", example: "N'oublie pas le parapluie, il pleut des cordes !"},
      {expr: "Avoir froid / chaud", meaning: "Estar com frio/calor.", example: "J'ai froid, ferme la fenêtre."},
    ],
    sentences: [
      "Aujourd'hui, il fait beau.",
      "En hiver, il fait froid.",
      "Il pleut beaucoup à Paris.",
      "Au Canada, il neige souvent.",
      "Le soleil brille.",
      "Le vent est fort.",
      "J'aime l'été à la plage.",
      "L'hiver, je porte un manteau.",
    ],
    grammar: {
      title: "Falar do Tempo com 'Il fait' e 'Il y a'",
      rules: [
        "Usamos <b>il fait</b> + adjetivo: il fait beau, il fait chaud, il fait froid.",
        "Usamos <b>il y a</b> + substantivo: il y a du vent, il y a du soleil, il y a des nuages.",
        "Verbos diretos: <b>il pleut</b> (chove), <b>il neige</b> (neva).",
      ],
      table: {
        headers: ["Estrutura", "Exemplo", "Tradução"],
        rows: [
          ["il fait + adj.", "Il fait chaud.", "Está calor."],
          ["il y a + subs.", "Il y a du vent.", "Está ventando."],
          ["verbo direto", "Il pleut.", "Está chovendo."],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'está chovendo' ?", a: "Il pleut", opts: ["Il neige", "Il pleut", "Il fait beau", "Il fait chaud"]},
      {q: "Como se diz 'o sol' em francês?", a: "Le soleil", opts: ["Le vent", "Le soleil", "L'été", "L'hiver"]},
      {q: "'Il ___ beau aujourd'hui.'", a: "fait", opts: ["est", "a", "fait", "y a"]},
      {q: "Como se diz 'inverno' ?", a: "L'hiver", opts: ["L'été", "L'hiver", "Le printemps", "L'automne"]},
      {q: "'Il ___ du vent.' (estrutura correta)", a: "y a", opts: ["fait", "est", "y a", "a"]},
    ],
    speak: [
      "Quel temps fait-il ?",
      "Il fait beau aujourd'hui.",
      "Il pleut beaucoup en hiver.",
      "J'aime le soleil de l'été.",
      "Il neige au Canada.",
    ],
  },

  {
    id: 210, title: "Les Directions", emoji: "🧭", lang: "fr",
    verbs: ["Tourner", "Aller", "Continuer", "Trouver"],
    vocab: [
      {en: "À gauche", pt: "À esquerda"},
      {en: "À droite", pt: "À direita"},
      {en: "Tout droit", pt: "Em frente / Reto"},
      {en: "Tournez", pt: "Vire (formal)"},
      {en: "La rue", pt: "A rua"},
      {en: "En face de", pt: "Em frente a / De frente para"},
      {en: "À côté de", pt: "Ao lado de"},
      {en: "Où est ?", pt: "Onde está/é?"},
    ],
    expressions: [
      {expr: "Excusez-moi", meaning: "Com licença.", example: "Excusez-moi, où est la gare ?"},
      {expr: "Pouvez-vous m'aider ?", meaning: "Você pode me ajudar?", example: "Pouvez-vous m'aider, s'il vous plaît ?"},
      {expr: "C'est loin ?", meaning: "É longe?", example: "Le musée, c'est loin d'ici ?"},
      {expr: "Tout près", meaning: "Bem perto.", example: "La boulangerie est tout près."},
    ],
    sentences: [
      "Tournez à gauche.",
      "Continuez tout droit.",
      "La pharmacie est à droite.",
      "Le musée est en face de l'hôtel.",
      "La banque est à côté de la poste.",
      "Où est la gare, s'il vous plaît ?",
      "Prenez la première rue à gauche.",
      "C'est tout près d'ici.",
    ],
    grammar: {
      title: "O Imperativo para Dar Direções",
      rules: [
        "Para dar instruções, usamos o <b>imperativo</b> (sem pronome).",
        "Forma <b>tu</b>: Tourne ! Va ! Prends ! (sem -s nos verbos -er).",
        "Forma <b>vous</b> (formal): Tournez ! Allez ! Prenez !",
      ],
      table: {
        headers: ["Verbo", "Tu", "Vous"],
        rows: [
          ["tourner", "Tourne !", "Tournez !"],
          ["aller", "Va !", "Allez !"],
          ["prendre", "Prends !", "Prenez !"],
          ["continuer", "Continue !", "Continuez !"],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'à esquerda' ?", a: "À gauche", opts: ["À droite", "À gauche", "Tout droit", "En face"]},
      {q: "Como se diz 'em frente' ?", a: "Tout droit", opts: ["À gauche", "À droite", "Tout droit", "À côté"]},
      {q: "Como perguntar 'onde está a estação' ?", a: "Où est la gare ?", opts: ["Quelle gare ?", "Où est la gare ?", "Comment la gare ?", "Quand la gare ?"]},
      {q: "'___ à droite !' (forma formal de 'vire')", a: "Tournez", opts: ["Tourne", "Tournez", "Tourner", "Tournes"]},
      {q: "Como se diz 'ao lado de' ?", a: "À côté de", opts: ["En face de", "À côté de", "Près de", "Loin de"]},
    ],
    speak: [
      "Excusez-moi, où est la gare ?",
      "Tournez à gauche, puis tout droit.",
      "La banque est à côté de la poste.",
      "C'est en face de l'hôtel.",
      "Prenez la première rue à droite.",
    ],
  },

  {
    id: 211, title: "Les Vêtements", emoji: "🛍️", lang: "fr",
    verbs: ["Porter", "Acheter", "Essayer", "Choisir"],
    vocab: [
      {en: "Un pantalon", pt: "Uma calça"},
      {en: "Une chemise", pt: "Uma camisa"},
      {en: "Une robe", pt: "Um vestido"},
      {en: "Des chaussures", pt: "Sapatos"},
      {en: "Un manteau", pt: "Um casaco"},
      {en: "Porter", pt: "Vestir / Usar"},
      {en: "La taille", pt: "O tamanho"},
      {en: "C'est combien ?", pt: "Quanto custa?"},
    ],
    expressions: [
      {expr: "Je peux essayer ?", meaning: "Posso provar?", example: "Cette robe, je peux essayer ?"},
      {expr: "Ça vous va bien", meaning: "Fica bem em você.", example: "Cette chemise, ça vous va bien !"},
      {expr: "C'est trop cher", meaning: "É muito caro.", example: "Non merci, c'est trop cher."},
      {expr: "Quelle est votre taille ?", meaning: "Qual é o seu tamanho?", example: "Quelle est votre taille, monsieur ?"},
    ],
    sentences: [
      "Je porte un pantalon noir.",
      "Elle achète une robe rouge.",
      "Tu essaies les chaussures.",
      "Il fait froid, je mets un manteau.",
      "Cette chemise est belle.",
      "C'est combien, ce pantalon ?",
      "Quelle est votre taille ?",
      "J'aime cette robe bleue.",
    ],
    grammar: {
      title: "Os Verbos em -ER no Presente",
      rules: [
        "A maioria dos verbos franceses termina em <b>-er</b> (porter, acheter, aimer).",
        "Retire o -er e adicione: <b>-e, -es, -e, -ons, -ez, -ent</b>.",
        "Exemplo: porter → je porte, tu portes, il porte, nous portons, vous portez, ils portent.",
      ],
      table: {
        headers: ["Pronome", "Porter", "Acheter"],
        rows: [
          ["je", "porte", "achète"],
          ["tu", "portes", "achètes"],
          ["il / elle", "porte", "achète"],
          ["nous", "portons", "achetons"],
          ["vous", "portez", "achetez"],
          ["ils / elles", "portent", "achètent"],
        ],
      },
    },
    quiz: [
      {q: "Como se diz 'uma camisa' ?", a: "Une chemise", opts: ["Un pantalon", "Une chemise", "Une robe", "Un manteau"]},
      {q: "Como perguntar 'quanto custa' ?", a: "C'est combien ?", opts: ["C'est quoi ?", "C'est combien ?", "C'est où ?", "C'est qui ?"]},
      {q: "'Je ___ un pantalon.' (vestir)", a: "porte", opts: ["porter", "porte", "portes", "portons"]},
      {q: "Como se diz 'sapatos' ?", a: "Des chaussures", opts: ["Un manteau", "Des chaussures", "Une robe", "Un pantalon"]},
      {q: "'Nous ___ des vêtements.' (comprar)", a: "achetons", opts: ["achète", "achetez", "achetons", "achètent"]},
    ],
    speak: [
      "Je porte une chemise bleue.",
      "C'est combien, ce pantalon ?",
      "Je peux essayer cette robe ?",
      "Quelle est votre taille ?",
      "J'achète un manteau noir.",
    ],
  },

  {
    id: 212, title: "Le Passé Composé", emoji: "⏪", lang: "fr",
    verbs: ["Avoir mangé", "Avoir fait", "Avoir vu", "Être allé"],
    vocab: [
      {en: "Hier", pt: "Ontem"},
      {en: "J'ai mangé", pt: "Eu comi"},
      {en: "J'ai fait", pt: "Eu fiz"},
      {en: "J'ai vu", pt: "Eu vi"},
      {en: "Je suis allé(e)", pt: "Eu fui"},
      {en: "J'ai parlé", pt: "Eu falei"},
      {en: "Déjà", pt: "Já"},
      {en: "La semaine dernière", pt: "Semana passada"},
    ],
    expressions: [
      {expr: "Hier soir", meaning: "Ontem à noite.", example: "Hier soir, j'ai vu un film."},
      {expr: "Il y a deux jours", meaning: "Há dois dias.", example: "Il y a deux jours, j'ai parlé à Marie."},
      {expr: "J'ai déjà fait", meaning: "Eu já fiz.", example: "J'ai déjà fait mes devoirs."},
      {expr: "Pas encore", meaning: "Ainda não.", example: "Tu as mangé ? — Non, pas encore."},
    ],
    sentences: [
      "Hier, j'ai mangé une pizza.",
      "La semaine dernière, j'ai vu mes amis.",
      "Il a fait ses devoirs.",
      "Nous avons parlé au téléphone.",
      "Elle est allée au cinéma.",
      "Je suis allé à Paris.",
      "Ils ont déjà mangé.",
      "Tu as fait du sport hier ?",
    ],
    grammar: {
      title: "Le Passé Composé (Pretérito Perfeito)",
      rules: [
        "Estrutura: <b>auxiliar (avoir/être) no presente</b> + <b>particípio passado</b>.",
        "A maioria dos verbos usa <b>avoir</b>: j'ai mangé, tu as vu, il a fait.",
        "Verbos de movimento e reflexivos usam <b>être</b>: je suis allé(e), elle est venue.",
        "Com <b>être</b>, o particípio concorda em gênero e número com o sujeito.",
      ],
      table: {
        headers: ["Verbo", "Auxiliar", "Exemplo"],
        rows: [
          ["manger", "avoir", "J'ai mangé."],
          ["faire", "avoir", "J'ai fait."],
          ["voir", "avoir", "J'ai vu."],
          ["aller", "être", "Je suis allé(e)."],
          ["parler", "avoir", "J'ai parlé."],
        ],
      },
    },
    quiz: [
      {q: "'Hier, j'___ une pizza.' (comer - passé composé)", a: "ai mangé", opts: ["mange", "ai mangé", "suis mangé", "mangeais"]},
      {q: "Qual auxiliar para 'aller' ?", a: "être", opts: ["avoir", "être", "faire", "aller"]},
      {q: "'Elle ___ au cinéma.' (ir - passé composé)", a: "est allée", opts: ["a allé", "est allée", "est allé", "a allée"]},
      {q: "Como se diz 'ontem' em francês?", a: "Hier", opts: ["Demain", "Aujourd'hui", "Hier", "Maintenant"]},
      {q: "'Nous ___ parlé.' (auxiliar correto)", a: "avons", opts: ["sommes", "avons", "êtes", "ont"]},
    ],
    speak: [
      "Hier, j'ai mangé au restaurant.",
      "La semaine dernière, je suis allé à Paris.",
      "Tu as vu ce film ?",
      "Nous avons parlé pendant deux heures.",
      "Elle a déjà fait ses devoirs.",
    ],
  },
];

if (typeof window !== 'undefined') window.LESSONS_FR = LESSONS_FR;
